replicaCount: 1

image:
  repository: ghcr.io/sebastianmarines/whirlpool_ac
  tag: sha256:171d90c7c8a7c81ddea7f696557895d350868f354dd1d0cbfc3fc99101b4d116
  pullPolicy: Always
  pullSecret: github-token

secret:
  name: whirlpool-creds
  usernameKey: username
  passwordKey: password
  clientSecretKey: client_secret