replicaCount: 1

image:
  repository: ghcr.io/sebastianmarines/whirlpool_ac
  tag: sha256:7be13a22a1fc7f74c745cd534487bd6420386dc4dc11db0036eed507b843e466
  pullPolicy: Always
  pullSecret: github-token