apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: whirlpool
  namespace: default
spec:
  selector:
    matchLabels:
      app: whirlpool
  endpoints:
    - interval: 30s
      port: whirlpool