apiVersion: v1
kind: Service
metadata:
  name: whirlpool
  labels:
    app: whirlpool
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
      name: whirlpool
  selector:
      app: whirlpool